version: "3.1"
services:
  elastic:
    image: elasticsearch:8.14.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./xwords.json:/data/xwords.json
